export const REQUEST_FLAG_PENDING = "REQUEST_FLAG_PENDING";
export const REQUEST_FLAG_SUCCESS = "REQUEST_FLAG_SUCCESS";
export const REQUEST_FLAG_FAILED = "REQUEST_FLAG_FAILED";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const UPDATE_TOTALQUESTION = "UPDATE_TOTALQUESTION";
export const UPDATE_FAILED = "UPDATE_FAILED";
export const RESTART = "RESTART";